#!/bin/bash

# Install AIDE
apt-get install -y aide

# Modify the AIDE configuration file to add rules to monitor /var/www and /tmp
sed -i '105i\/var\/www\tCONTENT' /etc/aide/aide.conf
sed -i '106i\/tmp\tCONTENT' /etc/aide/aide.conf

# Initialize the AIDE database with the new configuration
aideinit

# Remove the .new extension from the new database file
mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz

# Wait for AIDE database initialization to complete
sleep 10

# Copy the autogenerated config file to the /etc/aide directory
cp /var/lib/aide/aide.conf.autogenerated /etc/aide/aide.conf

# Build a new AIDE database
cp /var/lib/aide/aide.db.new /var/lib/aide/aide.db

# Create a cron job to run aide --check every 2 minutes
echo "*/2 * * * * /usr/sbin/aide --check" | crontab -
